### PR TITLE
update rails to 6.1.5.1

### PR DESCRIPTION
**Pull request by cdoyle-temple**

### CODE REVIEW

**Comment by sensei100** [comment]
@cdoyle-temple Were these migration files manually edited?  I know we have run into deployment issues in the past when that was done.

**Comment by cdoyle-temple** [comment]
The migrations are manually edited, and then run through rails db:migrate:reset so that the schema file is still auto-generated.

**Comment by cdoyle-temple** [comment]
oops

**Comment by sensei100** [comment]
@cdoyle-temple I really think that manually editing migration files is a practice that we should move away from.  This guide outlines how to change existing migrations in a safer way. https://edgeguides.rubyonrails.org/active_record_migrations.html

**Comment by cdoyle-temple** [comment]
I don't want to revert the existing migrations, dropping the fields and then recreating them correctly, we'd lose too much data. I could try adding a new migration to only target those two fields' type in the db.

**Comment by sensei100** [comment]
@cdoyle-temple You wouldn't be dropping existing migrations, you would be adding columns to existing tables.  The guide that I referenced earlier have directions for how to do that.

**Comment by cdoyle-temple** [comment]
@sensei100 It seems that the problem is with the CreateActiveStorageVariantRecords migration, and it won't run because of that. Any migration I write now, comes later and will not run until that CreateActiveStorageVariantRecords successfully completes.

**Comment by cdoyle-temple** [comment]
@sensei100 I'm not adding any columns in these corrections. Existing columns need to have their type changed.

**Comment by sensei100** [comment]
@cdoyle-temple I know that we have run into issues when manually editing migration files in the past.  

The guide specifically says, "If you have already run the migration, then you cannot just edit the migration and run the migration again: Rails thinks it has already run the migration and so will do nothing when you run bin/rails db:migrate. "  

I don't understand why you can't run a change_table migration to make the updates you need to ensure that we don't have issues with the existing databases.

**Comment by cdoyle-temple** [comment]
It's the order of the migrations. The failure is coming before any new migration I can write, i.e. an existing migration is now broken after a rails upgrade and is preventing the cascade of migrations that come after it. This prevents me from running the migration you suggest. I don't like it either, especially since it's activestorage generated migrations that are the issue. I'm open to suggestions but I can't see another way of handling it.

**Comment by sensei100** [comment]
@cdoyle-temple Those files are never meant to be modified manually.  It is why they are date-stamped.  Have you looked through the guide?  I feel like there has to be something there that would match what you need to do.

**Comment by cdoyle-temple** [comment]
@sensei100 If there is something I will gladly try it. I'm not seeing anything that would change an existing migration without creating a new migration. Any help doing that would be appreciated.

https://edgeguides.rubyonrails.org/active_record_migrations.html#changing-existing-migrations
https://edgeguides.rubyonrails.org/active_record_migrations.html#reverting-previous-migrations

**Comment by sensei100** [comment]
@cdoyle-temple Would something like this work? https://tosbourn.com/rails-migrate-change-column-type/

**Comment by cdoyle-temple** [comment]
@sensei100 That is a new migration.

**Comment by cdoyle-temple** [comment]
@sensei100 It is also exactly what I tried when I ran into the problem of the first migration failing and cancelling all remaining migrations. I can't run a new migration like this until that previous migration has run and that previous migration is not running unless the correct matching column type for the reference is specified in that migration. Here is some background on the nature of the issue: https://linuxtut.com/en/500f453c3b24030d800e/

**Pull request closed without merging**
