### PR TITLE
require aws sdk

### PR DESCRIPTION
**Pull request by quoideneuf**
this will fix the first error in production build. but build will still fail due to bad credentials.

### CODE REVIEW

**Comment by sensei100** [comment]
@quoideneuf Did the credentials I added not work?

**Comment by dkinzer** [comment]
Posted alternative PR(#61).  It builds but I didn't test if whatever aws is needed for still works.

**Comment by cdoyle-temple** [comment]
@quoideneuf Is this still needed? Jen merged David's #61 yesterday.

**Comment by dkinzer** [comment]
Yeah, #61 replaced this.

**Comment by quoideneuf** [comment]
👍

**Pull request closed without merging**
