### PR TITLE
revert test db settings for local testing

### PR DESCRIPTION
**Pull request by quoideneuf**

### CODE REVIEW

**Review by cdoyle-temple — CHANGES_REQUESTED** [review]
user, pass, and host are redundant here as this section inherits from default and there are no changes from those settings.

**Review by cdoyle-temple — CHANGES_REQUESTED** [review]
The database needs to be the only overridden value in the test section (currently "press6-test"). It shouldn't use the default db for testing.

**Review by cdoyle-temple — CHANGES_REQUESTED** [review]
Still not seeing the test db name specified.

test:
<<: *default
database: press6-test

**Comment by quoideneuf** [comment]
> Still not seeing the test db name specified.
> 
> test:
> <<: *default
> database: press6-test

Ok, how about now?

**Review by cdoyle-temple — APPROVED** [review]
That won't hurt having the variable in but it is unnecessary. It's just the local test environment and doesn't use environment variables, much like the development section above it, it just needs a db name for the test suite to populate using FactoryBot without interfering with the development db.

**Pull request merged**
