### PR TITLE
roll back ruby

### PR DESCRIPTION
**Pull request by cdoyle-temple**

### CODE REVIEW

**Comment by sensei100** [comment]
@cdoyle-temple I don't think that you can roll back the ruby version without updating the image that is in harbor.  And they pretty much update ruby to the latest version whenever it comes out.

**Comment by cdoyle-temple** [comment]
@sensei100 Was trying to go back to the last successful build. The first build that failed, and it's been failing for two weeks, was when the ruby version was updated from 3.1.0 to 3.1.1. I can't find much evidence otherwise what is causing the failed builds.

**Comment by sensei100** [comment]
@cdoyle-temple The builds are failing because of security vulnerabilities coming from esbuild.  Is it possible to not use that package in this project?  I noticed that it isn't in manifold or librarysearch.

**Comment by cdoyle-temple** [comment]
@sensei100 Esbuild is the javascript bundler. It's also in manifold but librarysearch current doesn't use it as it's not on rails 7 yet. It can't be removed unless we move to importmaps or back to webpacker. Manifold isn't failing the builds though.

**Comment by sensei100** [comment]
@cdoyle-temple I would look at how the configuration is different between manifold and Press-6.  We have 4 projects in Kubernetes that are all using the same ruby docker image and Press-6 is the only one failing.  All of the errors are related to esbuild.  I don't think that trying to roll back the ruby version will help in this situation and the only way you could roll it back would be to change the docker image because that is where the ruby version is set.

**Comment by cdoyle-temple** [comment]
@sensei100 I can close this PR. I wanted to test on QA if it would make a difference, but it doesn't seem the right way to go.

**Comment by sensei100** [comment]
@cdoyle-temple What I am trying to communicate is that none of these changes would actually roll back the ruby version.  That is set by the image we are using and that did not get changed in this PR.

**Comment by cdoyle-temple** [comment]
@sensei100 Yes, I understand. And I will close this PR as any further work on it to change the ruby version is not the right way to proceed.

**Pull request closed without merging**
